# ATTRIBUTION-AI: Largely attributable to ChatGPT o1-preview 2024-11-20 .

name: _delete-partFiles (Dry Run)

on:
    workflow_dispatch:
      inputs:
        release_tag:
          description: 'Release tag (e.g., build-10889308814-1)'
          required: true

jobs:
  delete_part_files_dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: List .part* Files from Release (Dry Run)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.inputs.release_tag }}
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          REPO=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          
          echo "Fetching release information for tag: ${RELEASE_TAG}"

          RESPONSE=$(curl -sSL \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${OWNER}/${REPO}/releases/tags/${RELEASE_TAG}")

          if echo "${RESPONSE}" | grep -q '"message": "Not Found"'; then
            echo "Error: Release '${RELEASE_TAG}' not found."
            exit 1
          fi

          echo "Listing .part* files that would be deleted:"
          echo "${RESPONSE}" | jq -r '.assets[] | select(.name | test("\\.part.*$")) | "- \(.name) (ID: \(.id))"'