
# WARNING: May be untested .
# WARNING: As much as ~100GB temporary storage may be required.
# https://github.community/t/bigger-github-hosted-runners-disk-space/17267
#  2vCPU, 7GiB RAM, 14GiB SSD
#  16vCPU, 56GiB RAM, 112GiB SSD
# Github Actions may have a higher capacity (presumably HDD) or 'C:\' disk, contrasted with the small 'Temp storage' SSD. Apparently does not apply to Linux 'runners'.
# BuildJet may use some larger instances, at much higher price. Apparently BuildJet instances have 61GB .
# Cloud VPS, through cloud-init and other APIs, may be much more cost effective.

# ATTENTION: NOTICE: Consider replacing the current directory with a symlink to a larger filesystem, before checkout of repository.

name: build


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: write
  checks: read
  contents: write
  deployments: read
  issues: none
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read


on:
  #push:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '5 7 * * 6'
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 2,4'
    #- cron: '5 1 * * 2'
    #- cron: '5 1 * * 4'
    #- cron: '5 1 * * 5'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Adding 'core' and 'live' images could be separate jobs if necessary.
# Conveniently separable code for 'experiment', and may add additional build time.
# Disadvantage of downloading back from rclone, and duplicating such preparation as deleting files from CI.
# Better to just copy relevant markup to separate CI config files, which would be the desired end result anyway.
# https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
# https://stackoverflow.com/questions/68187987/github-actions-job-timeout
#  'Each job in a workflow can run for up to 6 hours'
  #core:
    #if: ${{ always() }}
    #needs: [build]
  #live:
    #if: ${{ always() }}
    #needs: [build, core]


jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    #  '7 GB of RAM memory'
    #  '14 GB of SSD disk space'
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04
    #runs-on: ubuntu-20.04
    #runs-on: ubuntu-18.04
    # Apparently both 'buildjet-2vcpu-ubuntu-2004' and 'buildjet-16vcpu-ubuntu-2004' have 61GB .
    #runs-on: buildjet-2vcpu-ubuntu-2004
    #runs-on: buildjet-16vcpu-ubuntu-2004
    # https://github.com/easimon/maximize-build-space
    steps:
      - name: users
        shell: bash
        run: |
          sudo -u ubuntu -n bash -c 'sudo -n useradd runner --non-unique -u $UID -g $UID' || true
          sudo -u ubuntu -n bash -c 'sudo -n groupadd runner --non-unique -g $UID' || true
          sudo -u runner -n bash -c 'sudo -n echo $USER $UID' || true
          true
      # Apparently may increase buildJet 'runner' to 77GB (instead of 61GB).
      # Apparently may increase Github Actions 'runner' to 59GB (instead of 31GB) .
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          #root-reserve-mb: 512
          root-reserve-mb: 4500
          #temp-reserve-mb: 100
          temp-reserve-mb: 300
          #swap-size-mb: 128
          swap-size-mb: 192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ! ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud && exit 1
          true
          #! sudo -n apt-get -y clean && exit 1
          df -h
          df -h /
        timeout-minutes: 90
      #- name: changeDisk
        #shell: bash
        #run: |
          #false
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ! ./ubiquitous_bash.sh _getMinimal_cloud && exit 1
          true
          #! sudo -n apt-get -y clean && exit 1
          df -h
          df -h /
        timeout-minutes: 355
      # For VBoxManage for _convert . Otherwise historically not apparently necessary.
      - name: _getMost
        shell: bash
        run: |
          ! ./ubiquitous_bash.sh _getMost && exit 1
          true
          #! sudo -n apt-get -y clean && exit 1
          df -h
          df -h /
        timeout-minutes: 355
      #- name: _create_ubDistBuild
        #shell: bash
        #run: |
          #./_create_ubDistBuild | sudo -n tee ./_local/_create_ubDistBuild.log
      - name: mkdir _local
        shell: bash
        run: |
          mkdir -p ./_local
      - name: _true
        shell: bash
        run: |
          ./_true | sudo -n tee ./_local/_true.log && exit ${PIPESTATUS[0]}
      - name: _false
        shell: bash
        run: |
          ( ! ./_false ) | sudo -n tee ./_local/_false.log && exit ${PIPESTATUS[0]}
      - name: _create_ubDistBuild-create
        shell: bash
        run: |
          ./_create_ubDistBuild-create | sudo -n tee ./_local/_create_ubDistBuild-create.log && exit ${PIPESTATUS[0]}
      - name: _create_ubDistBuild-rotten_install
        shell: bash
        run: |
          ./_create_ubDistBuild-rotten_install | sudo -n tee ./_local/_create_ubDistBuild-rotten_install.log && exit ${PIPESTATUS[0]}
      - name: _chroot_test
        shell: bash
        run: |
          ./_chroot_test | sudo -n tee ./_local/_chroot_test.log && exit ${PIPESTATUS[0]}
      - name: _create_ubDistBuild-bootOnce
        shell: bash
        run: |
          ./_create_ubDistBuild-bootOnce | sudo -n tee ./_local/_create_ubDistBuild-bootOnce.log && exit ${PIPESTATUS[0]}
      - name: _create_ubDistBuild-rotten_install-core
        shell: bash
        run: |
          ./_create_ubDistBuild-rotten_install-core | sudo -n tee ./_create_ubDistBuild-rotten_install-core.log && exit ${PIPESTATUS[0]}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: _create_ubDistBuild-install-ubDistBuild
        shell: bash
        run: |
          ./_create_ubDistBuild-install-ubDistBuild | sudo -n tee ./_create_ubDistBuild-install-ubDistBuild.log && exit ${PIPESTATUS[0]}
      #- name: _create_ubDistBuild-bootOnce
        #shell: bash
        #run: |
          #./_create_ubDistBuild-bootOnce | sudo -n tee ./_local/_create_ubDistBuild-bootOnce.log
      - name: _package_ubDistBuild_image
        shell: bash
        run: |
          ./_package_ubDistBuild_image | sudo -n tee ./_local/_package_ubDistBuild_image.log && exit ${PIPESTATUS[0]}
      - name: _ubDistBuild_split
        shell: bash
        run: |
          ./ubiquitous_bash.sh _ubDistBuild_split | sudo -n tee ./_lib/_ubDistBuild_split.log && exit ${PIPESTATUS[0]}
        timeout-minutes: 355
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            #./_local/package_image.tar.xz.part*
            ./_local/ops.sh
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part00
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part01
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part02
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part03
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part04
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part05
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part06
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part07
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part08
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part09
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part10
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/package_image.tar.xz.part11
      #- name: _croc_ubDistBuild_image_out
        #shell: bash
        #run: |
          #./ubiquitous_bash.sh _croc_ubDistBuild_image_out | sudo -n tee ./_lib/_croc_ubDistBuild_image_out.log
        #timeout-minutes: 355
      - name: _convert-live
        shell: bash
        run: |
          export current_diskConstrained="true"
          ./ubiquitous_bash.sh _convert_rm
          ./ubiquitous_bash.sh _convert-live | sudo -n tee ./_convert-live.log && exit ${PIPESTATUS[0]}
          ./ubiquitous_bash.sh _safeRMR ./_local/livefs
      - name: _ubDistBuild_split-live
        shell: bash
        run: |
          ./ubiquitous_bash.sh _ubDistBuild_split-live
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part00
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part01
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part02
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part03
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part04
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part05
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part06
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part07
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part08
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part09
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part10
      - name: release! core
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ./_local/vm-live.iso.part11
      #- name: _assessment
        #shell: bash
        #run: |
          #./_assessment | sudo -n tee ./_local/_assessment.log && exit ${PIPESTATUS[0]}
      #- name: Setup tmate session
        #if: ${{ failure() }}
        #uses: mxschmitt/action-tmate@v3
        ## ssh -i <path-to-key> <tmate-connection-string>
        #with:
          #limit-access-to-actor: true
        #timeout-minutes: 25


